version: "3"
services:
  angular_cli:
    #build: docker/ng-cli
    image: trion/ng-cli:latest
    container_name: "angular_cli"
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    ports:
      - 4200:4200
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0"
#  angular_karma:
#   image: trion/ng-cli-karma:latest
 #   #build: docker/ng-cli-karma
 #   container_name: "angular_karma"
 #   volumes:
  #    - .:/usr/app/
  #    - ./log/:/tmp/
  #  working_dir: /usr/app/
 #   ports:
 #     - 9876:9876
 #   command: >
 #     bash -c "ng test"
  angular_e2e:
    image: trion/ng-cli-e2e:latest
    #build: docker/ng-cli-e2e
    container_name: "angular_e2e"
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    command: >
      bash -c "ng e2e"
